version: "3.8"

services:
  frontend:
    build: ./app
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "8700:3000"
    working_dir: /root/app
    volumes:
      - ./app:/root/app:cached

  mongodb: #--name
    image: mongo #--image
    restart: always
    ports:
      - 7233:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-gui:
    image: mongo-express
    restart: always
    ports:
      - 7234:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
