version: "3.8"

services:
  frontend:
    build: ./app
    environment:
      - MONGODB_SERVER=mongodb
      - MONGODB_ADMINUSERNAME=admin
      - MONGODB_ADMINPASSWORD=password
      - DB_NAME=basicDB
    ports:
      - "8700:3000"
    depends_on:
      - mongodb
    # working_dir: /root/app
    # volumes:
    #   - ./app:/root/app:cached

  mongodb:
    image: mongo
    ports:
      - 7233:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  mongo-gui:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 7234:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: "local"
